import Layout from '../components/Layout';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <Layout title="Terms & Conditions" subtitle="Terms of service and usage guidelines">
      <div className="card" style={{ maxWidth: 800, margin: '0 auto', padding: 32 }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 4 }}>
          Terms &amp; Conditions
        </h1>
        <p style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 24 }}>
          Last updated: September 17, 2026
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
          <section>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using FINWISE, you agree to these Terms & Conditions. If you do not agree, please discontinue using the application.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>
              2. Educational & Planning Tool Only
            </h2>
            <p>
              FINWISE provides mathematical calculations, scenario modeling, and ratio analysis based strictly on the figures entered by the user. FINWISE does not provide formal certified financial or legal advice.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>
              3. Accuracy of Calculations
            </h2>
            <p>
              All projections (such as months remaining to reach a financial goal) are mathematical estimates based on constant cash flows. Real market returns, tax adjustments, and inflation will vary over time.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>
              4. Limitation of Liability
            </h2>
            <p>
              FINWISE and its developers are not liable for financial decisions made based on outputs generated by this tool. Always consult a qualified financial professional for critical investments.
            </p>
          </section>
        </div>

        <div style={{ marginTop: 32, paddingTop: 16, borderTop: '1px solid var(--border)' }}>
          <Link to="/dashboard" className="btn btn-secondary">
            ← Back to Dashboard
          </Link>
        </div>
      </div>
    </Layout>
  );
}
